-- v0.2.30：数据目录迁移时的路径更新记录。
-- 不变更表结构，不对当前源数据库执行。应用先用 SQLite VACUUM INTO
-- 生成一致性快照，再在目标暂存副本的一个事务中按主键参数化更新。
-- 以下为程序使用的语句模板记录，不是需要手工执行的部署脚本。
-- :value 由完整目录边界映射产生；外部路径、密码及历史内容不作全库替换。
-- :key / :id 为原记录主键；已是目标路径的记录不会重复更新。

-- UPDATE installed SET install_path = :value WHERE key = :key;
-- UPDATE installed SET config_path = :value WHERE key = :key;
-- UPDATE sites SET root_dir = :value WHERE id = :id;
-- UPDATE sites SET runtime = :value WHERE id = :id;
-- UPDATE sites SET php_overrides = :value WHERE id = :id;
-- UPDATE certs SET cert_path = :value WHERE id = :id;
-- UPDATE certs SET key_path = :value WHERE id = :id;
-- UPDATE cron_jobs SET command = :value WHERE id = :id;
-- UPDATE cert_automations SET data = :value WHERE id = :id;

-- sites.runtime 仅修改 cwd 和 command；保留其它 JSON 字段。
-- cert_automations.data 仅修改本地部署目标的 certPath/keyPath/script。
-- pathEnvDirs 保留原值，用于首次启动新目录时精确移除原有托管 PATH 条目。

-- v0.2.32：迁移子进程初始化失败且已确认清理后，恢复目标副本的 PATH 记录。
-- 仅目标 SQLite 副本的 settings 表；没有表结构变更，不需要手工执行。
-- :value 为启动前保存的 pathEnvDirs JSON 数组，幂等恢复后供下一次激活使用。
-- INSERT INTO settings(key,value) VALUES('pathEnvDirs',:value)
-- ON CONFLICT(key) DO UPDATE SET value=:value;

-- v0.2.35：证书自动化异常中断恢复与配置更新记录。
-- 沿用当前 SQLite cert_automations 表，不新增表或字段，不需手工部署。
-- 应用取得同一任务的操作系统独占锁后，重新读取该行；只有 issuing/manual_wait
-- 且已没有锁主的任务才按中断恢复。JSON 中将 state 置为 error、enabled 置为 false，
-- 暂停 nextRenewAt，保留 manualRecords、证书结果，并新增一条有上限的执行历史。
-- 重复检查已恢复的记录不会重复写入；其它窗口仍持锁时不执行恢复。
-- 配置编辑也在该锁下核对 updatedAt，拒绝旧表单并保留后台维护的运行字段。
-- 以下是现有参数化写入模板；:data 为完整序列化 JSON，:updated_at 单调递增。
-- INSERT INTO cert_automations(id,data,updated_at) VALUES(:id,:data,:updated_at)
-- ON CONFLICT(id) DO UPDATE SET data=:data, updated_at=:updated_at;

-- v0.2.39：ACME 证书自动化按 SAN 同步所有匹配的本地 HTTPS 站点，沿用
-- cert_automations.data JSON；无表结构变更，无需手工执行。
-- UPDATE cert_automations SET data = :value WHERE id = :id;
-- 删除入口先检查任务存在和执行锁；账号密钥删除失败保留记录，入库失败恢复密钥。
-- DELETE FROM cert_automations WHERE id=:id;

-- v0.2.36：证书签发与部署分阶段记录。沿用 SQLite cert_automations.data JSON，
-- 不新增列或表；以下是应用运行时参数化语句的记录，不需手工执行。
-- 新增 deploymentId / localDeployResult 使用默认值兼容旧数据；私钥材料只保存在
-- certs/acme 的原子文件中，不放入 JSON 或配置导出。
-- 持同一任务的独占锁逐目标保存结果，updated_at 单调递增。
-- 部署中断恢复为 deploy_interrupted 并暂停；正常目标失败为 deploy_error。
-- 旧版 ok 但有失败目标、或远程专用证书有效期未知的记录，在持锁复核后仅纠正一次。
-- 导入配置时清空来源 deploymentId、localDeployResult、certId、issuedAt、expiresAt
-- 及目标的 lastResult，保持关闭；没有原证书材料时不能声称可重试部署。
-- INSERT INTO cert_automations(id,data,updated_at) VALUES(:id,:data,:updated_at)
-- ON CONFLICT(id) DO UPDATE SET data=:data, updated_at=:updated_at;
-- 删除前保存账号与材料原文，删除文件或记录失败则恢复，成功部署的站点证书不删除。
-- DELETE FROM cert_automations WHERE id=:id;

-- v0.2.37：SSH / 本地证书部署配置与不确定结果。仍使用 cert_automations.data JSON，
-- 没有表结构变更；以下为程序参数化语句记录，不需手工执行。
-- SSH 配置使用 auth，新增 identityFile、keyPassphrase、hostFingerprint、timeoutSec；
-- 兼容 privateKey 登录路径，keyPath 只表示远程证书私钥输出位置。
-- 调度前校验失败会暂停并记录历史；已有签发批次保持 deploy_error，可修正配置后重试。
-- 脚本超时/退出异常或远程发布结果不确定时保存目标结果，再进入 deploy_interrupted，
-- 关闭自动续签，保留已签发材料和其它已成功目标，避免自动重放。
-- INSERT INTO cert_automations(id,data,updated_at) VALUES(:id,:data,:updated_at)
-- ON CONFLICT(id) DO UPDATE SET data=:data, updated_at=:updated_at;
-- 数据目录迁移只在目标 SQLite 副本中重写 SSH 的 identityFile/privateKey，
-- 不改远程 certPath/keyPath/script；本地部署仍按原规则重写本机路径和命令。
-- deploying 与 issuing/manual_wait 一样拒绝迁移。
-- UPDATE cert_automations SET data=:value WHERE id=:id;

-- v0.2.38：证书任务共用资源等待，沿用 SQLite cert_automations.data JSON。
-- 没有表结构变更；以下仅记录应用现有参数化写入，不需手工执行。
-- 自动任务拿不到 DNS/部署输出资源锁时，将 state 设置为 waiting/deploy_waiting，
-- nextRenewAt 延后一分钟，保留批次、证书、目标结果、历史、lastRunAt 和 failCount。
-- 不会把等待保存为一次失败或发起新的 CA 请求；资源锁本身是空的 OS 文件锁。
-- 关闭自动续签时取消等待：waiting 回 idle，deploy_waiting 回 deploy_error，
-- 已签发材料仍供手动重试。实际开始执行后清除等待原因并按原流程记录运行结果。
-- INSERT INTO cert_automations(id,data,updated_at) VALUES(:id,:data,:updated_at)
-- ON CONFLICT(id) DO UPDATE SET data=:data, updated_at=:updated_at;

-- v0.2.40：站点实际证书文件与 certs 元数据保持一致；仍为 SQLite，无表结构变化。
-- 以下为运行时参数化模板，不是手工部署脚本。所有目标记录在同一事务中提交。
-- 先删除将被替换的同路径 site/acme 记录，再逐一写入新的实际证书信息；
-- 任一条失败回滚整个事务，调用方同时恢复已写入的证书/私钥文件。
-- 本地自签、ACME 同步、旧 SAN 副本恢复以及站点编辑失败恢复沿用同一入口。
-- DELETE FROM certs WHERE cert_path=:cert_path AND kind IN ('site','acme');
-- INSERT INTO certs(id,kind,subject,sans,not_before,not_after,cert_path,key_path)
-- VALUES(:id,:kind,:subject,:sans,:not_before,:not_after,:cert_path,:key_path)
-- ON CONFLICT(id) DO UPDATE SET kind=:kind, subject=:subject, sans=:sans,
-- not_before=:not_before, not_after=:not_after, cert_path=:cert_path, key_path=:key_path;
-- 不读取/修改真实用户数据库，不引入 migration；已匹配记录重复执行后结果一致。
