-- v0.2.30：数据目录迁移时的路径更新记录。
-- 不变更表结构，不对当前源数据库执行。应用先用 SQLite VACUUM INTO
-- 生成一致性快照，再在目标暂存副本的一个事务中按主键参数化更新。
-- 以下为程序使用的语句模板记录，不是需要手工执行的部署脚本。
-- :value 由完整目录边界映射产生；外部路径、密码及历史内容不作全库替换。
-- :key / :id 为原记录主键；已是目标路径的记录不会重复更新。

-- UPDATE installed SET install_path = :value WHERE key = :key;
-- UPDATE installed SET config_path = :value WHERE key = :key;
-- UPDATE sites SET root_dir = :value WHERE id = :id;
-- UPDATE sites SET runtime = :value WHERE id = :id;
-- UPDATE sites SET php_overrides = :value WHERE id = :id;
-- UPDATE certs SET cert_path = :value WHERE id = :id;
-- UPDATE certs SET key_path = :value WHERE id = :id;
-- UPDATE cron_jobs SET command = :value WHERE id = :id;
-- UPDATE cert_automations SET data = :value WHERE id = :id;

-- sites.runtime 仅修改 cwd 和 command；保留其它 JSON 字段。
-- cert_automations.data 仅修改本地部署目标的 certPath/keyPath/script。
-- pathEnvDirs 保留原值，用于首次启动新目录时精确移除原有托管 PATH 条目。

-- v0.2.32：迁移子进程初始化失败且已确认清理后，恢复目标副本的 PATH 记录。
-- 仅目标 SQLite 副本的 settings 表；没有表结构变更，不需要手工执行。
-- :value 为启动前保存的 pathEnvDirs JSON 数组，幂等恢复后供下一次激活使用。
-- INSERT INTO settings(key,value) VALUES('pathEnvDirs',:value)
-- ON CONFLICT(key) DO UPDATE SET value=:value;

-- v0.2.35：证书自动化异常中断恢复与配置更新记录。
-- 沿用当前 SQLite cert_automations 表，不新增表或字段，不需手工部署。
-- 应用取得同一任务的操作系统独占锁后，重新读取该行；只有 issuing/manual_wait
-- 且已没有锁主的任务才按中断恢复。JSON 中将 state 置为 error、enabled 置为 false，
-- 暂停 nextRenewAt，保留 manualRecords、证书结果，并新增一条有上限的执行历史。
-- 重复检查已恢复的记录不会重复写入；其它窗口仍持锁时不执行恢复。
-- 配置编辑也在该锁下核对 updatedAt，拒绝旧表单并保留后台维护的运行字段。
-- 以下是现有参数化写入模板；:data 为完整序列化 JSON，:updated_at 单调递增。
-- INSERT INTO cert_automations(id,data,updated_at) VALUES(:id,:data,:updated_at)
-- ON CONFLICT(id) DO UPDATE SET data=:data, updated_at=:updated_at;

-- v0.2.39：ACME 证书自动化按 SAN 同步所有匹配的本地 HTTPS 站点，沿用
-- cert_automations.data JSON；无表结构变更，无需手工执行。
-- UPDATE cert_automations SET data = :value WHERE id = :id;
-- 删除入口先检查任务存在和执行锁；账号密钥删除失败保留记录，入库失败恢复密钥。
-- DELETE FROM cert_automations WHERE id=:id;

-- v0.2.36：证书签发与部署分阶段记录。沿用 SQLite cert_automations.data JSON，
-- 不新增列或表；以下是应用运行时参数化语句的记录，不需手工执行。
-- 新增 deploymentId / localDeployResult 使用默认值兼容旧数据；私钥材料只保存在
-- certs/acme 的原子文件中，不放入 JSON 或配置导出。
-- 持同一任务的独占锁逐目标保存结果，updated_at 单调递增。
-- 部署中断恢复为 deploy_interrupted 并暂停；正常目标失败为 deploy_error。
-- 旧版 ok 但有失败目标、或远程专用证书有效期未知的记录，在持锁复核后仅纠正一次。
-- 导入配置时清空来源 deploymentId、localDeployResult、certId、issuedAt、expiresAt
-- 及目标的 lastResult，保持关闭；没有原证书材料时不能声称可重试部署。
-- INSERT INTO cert_automations(id,data,updated_at) VALUES(:id,:data,:updated_at)
-- ON CONFLICT(id) DO UPDATE SET data=:data, updated_at=:updated_at;
-- 删除前保存账号与材料原文，删除文件或记录失败则恢复，成功部署的站点证书不删除。
-- DELETE FROM cert_automations WHERE id=:id;

-- v0.2.37：SSH / 本地证书部署配置与不确定结果。仍使用 cert_automations.data JSON，
-- 没有表结构变更；以下为程序参数化语句记录，不需手工执行。
-- SSH 配置使用 auth，新增 identityFile、keyPassphrase、hostFingerprint、timeoutSec；
-- 兼容 privateKey 登录路径，keyPath 只表示远程证书私钥输出位置。
-- 调度前校验失败会暂停并记录历史；已有签发批次保持 deploy_error，可修正配置后重试。
-- 脚本超时/退出异常或远程发布结果不确定时保存目标结果，再进入 deploy_interrupted，
-- 关闭自动续签，保留已签发材料和其它已成功目标，避免自动重放。
-- INSERT INTO cert_automations(id,data,updated_at) VALUES(:id,:data,:updated_at)
-- ON CONFLICT(id) DO UPDATE SET data=:data, updated_at=:updated_at;
-- 数据目录迁移只在目标 SQLite 副本中重写 SSH 的 identityFile/privateKey，
-- 不改远程 certPath/keyPath/script；本地部署仍按原规则重写本机路径和命令。
-- deploying 与 issuing/manual_wait 一样拒绝迁移。
-- UPDATE cert_automations SET data=:value WHERE id=:id;

-- v0.2.38：证书任务共用资源等待，沿用 SQLite cert_automations.data JSON。
-- 没有表结构变更；以下仅记录应用现有参数化写入，不需手工执行。
-- 自动任务拿不到 DNS/部署输出资源锁时，将 state 设置为 waiting/deploy_waiting，
-- nextRenewAt 延后一分钟，保留批次、证书、目标结果、历史、lastRunAt 和 failCount。
-- 不会把等待保存为一次失败或发起新的 CA 请求；资源锁本身是空的 OS 文件锁。
-- 关闭自动续签时取消等待：waiting 回 idle，deploy_waiting 回 deploy_error，
-- 已签发材料仍供手动重试。实际开始执行后清除等待原因并按原流程记录运行结果。
-- INSERT INTO cert_automations(id,data,updated_at) VALUES(:id,:data,:updated_at)
-- ON CONFLICT(id) DO UPDATE SET data=:data, updated_at=:updated_at;

-- v0.2.40：站点实际证书文件与 certs 元数据保持一致；仍为 SQLite，无表结构变化。
-- 以下为运行时参数化模板，不是手工部署脚本。所有目标记录在同一事务中提交。
-- 先删除将被替换的同路径 site/acme 记录，再逐一写入新的实际证书信息；
-- 任一条失败回滚整个事务，调用方同时恢复已写入的证书/私钥文件。
-- 本地自签、ACME 同步、旧 SAN 副本恢复以及站点编辑失败恢复沿用同一入口。
-- DELETE FROM certs WHERE cert_path=:cert_path AND kind IN ('site','acme');
-- INSERT INTO certs(id,kind,subject,sans,not_before,not_after,cert_path,key_path)
-- VALUES(:id,:kind,:subject,:sans,:not_before,:not_after,:cert_path,:key_path)
-- ON CONFLICT(id) DO UPDATE SET kind=:kind, subject=:subject, sans=:sans,
-- not_before=:not_before, not_after=:not_after, cert_path=:cert_path, key_path=:key_path;
-- 不读取/修改真实用户数据库，不引入 migration；已匹配记录重复执行后结果一致。

-- v0.2.41：站点直接选择已签发的 ACME 主证书。
-- 沿用 SQLite sites.runtime JSON，可选 acmeCertId 与 importedCertId 互斥；
-- 旧记录缺少 acmeCertId 时仍使用原有证书来源。没有新增表、列、索引或 migration。
-- 以下仅记录现有站点保存语句的相关部分，不需要手工执行；完整 runtime 保留其它字段。
-- UPDATE sites SET runtime=:runtime, updated_at=:updated_at WHERE id=:id;
-- 文件/记录/域名覆盖校验失败不保存选择，后续应用失败恢复原 runtime 和配置。
-- 导入只含绑定信息，不含私钥；所选证书未恢复时在任何导入写入前拒绝。

-- v0.2.44：网站证书监控使用规范化端点、并发执行锁与结果版本比较。
-- 继续使用 SQLite cert_monitors.data JSON，新增可选 notificationError；无表结构变更。
-- 以下是应用运行时参数化语句记录，不需手工执行；没有操作真实用户数据库。
-- 新增/导入先规范化 host 和 port，BEGIN IMMEDIATE 内读取已有记录去重，仅 INSERT；
-- 导入不携带来源机器的状态、签发者、到期时间、检查时间或告警错误，重复端点跳过。
-- INSERT INTO cert_monitors(id,data,updated_at) VALUES(:id,:data,:updated_at);
-- 网络探测、推送重试完成后均只更新原版本；删除或编辑之后不重新创建/覆盖记录。
-- UPDATE cert_monitors SET data=:data,updated_at=:updated_at
-- WHERE id=:id AND updated_at=:expected_revision;
-- DELETE FROM cert_monitors WHERE id=:id;
-- 告警方式与地址在同一事务保存；第二项写入失败时整体回滚。
-- INSERT INTO settings(key,value) VALUES(:key,:value)
-- ON CONFLICT(key) DO UPDATE SET value=:value;
-- :key 依次为 monitorNotifyKind、monitorNotifyUrl；不把实际 Webhook 凭据写入此文件。

-- v0.2.47：通用服务的配置准备完成后，原子保存端口分配及自动回落覆盖。
-- 沿用 SQLite port_assign、settings 表，无新增表、列、索引或 migration。
-- 以下为应用运行时参数化 SQL 记录，无需手工执行；本轮未操作真实用户数据库。
-- BEGIN;
-- INSERT INTO port_assign(service_id,base_port) VALUES(:service_id,:port)
-- ON CONFLICT(service_id) DO UPDATE SET base_port=:port;
-- 仅发生自动回落时执行下一句，:key 为 portOverride.<service_id>，:value 为端口数字文本。
-- INSERT INTO settings(key,value) VALUES(:key,:value)
-- ON CONFLICT(key) DO UPDATE SET value=:value;
-- COMMIT;
-- 任一句失败整体回滚；重复保存相同端口保持幂等，配置校验失败不保存端口。

-- v0.2.49：SFTPGo 在首次成功启动并确认 SFTP/Web 两端口归属后绑定原配置目录。
-- 沿用 SQLite settings 表，已核对 Store::open 中的表定义；无表结构变更、无 migration。
-- 相对路径允许整个 NiceEnv 数据目录迁移后继续定位；不复制数据库、不重新生成主机密钥。
-- 以下为应用运行时的参数化 SQL 记录，不需要手工执行；本轮未操作用户实际数据库。
-- INSERT INTO settings(key,value) VALUES(:key,:value)
-- ON CONFLICT(key) DO UPDATE SET value=:value;
-- :key = 'sftpgoConfigDir'，:value = 'etc/sftpgo/shared' 或已确认的原版本配置目录。
-- 首次配置校验/启动失败不保存绑定；绑定写入失败停止本次进程，保留原目录供重试。
-- 后续启动必须使用原绑定，目录、配置或可确认的本地状态缺失时拒绝创建空库。
-- v0.2.55：SFTPGo 配置目录选择复用上面的 settings 幂等写入，无 schema 变更。
-- 用户明确选择已有目录时，先在生命周期锁内确认服务已停止、版本及旧绑定未变化，
-- 再只读复查配置/数据库/主机密钥，成功才保存 :key='sftpgoConfigDir'。
-- 选择操作不启动服务、不复制或合并原数据；默认启动流程仍在健康启动后保存首次绑定。

-- v0.2.143：安装新版本时保留实际默认选择，防止默认服务和跟随默认的 PATH 隐式换版。
-- 已核对 Store::open 的 SQLite installed/settings 表定义，无表结构变更或 migration。
-- 以下为应用运行时参数化 SQL 记录，不需要手工执行；本轮不操作真实用户数据库。
-- 在同一个写事务内先读取当前选择及安装版本，再提交安装记录和默认选择。
-- :active_version 为现有有效选择；缺失/失效时取提交前最高已装版本；首次安装取 :version。
-- BEGIN IMMEDIATE;
-- INSERT INTO installed(key,id,version,category,install_path,config_path,installed_at)
-- VALUES(:package_key,:id,:version,:category,:install_path,:config_path,:installed_at)
-- ON CONFLICT(key) DO UPDATE SET
--   install_path=:install_path, config_path=:config_path, installed_at=:installed_at;
-- 仅默认设置与上述选择不一致时执行；:active_key = 'active' || :id || 'Version'。
-- INSERT INTO settings(key,value) VALUES(:active_key,:active_version)
-- ON CONFLICT(key) DO UPDATE SET value=:active_version;
-- COMMIT;
-- 任一写入失败均回滚；下载期间用户新选的默认版本在提交时读取并保留。
-- pathEnvVersions 的独立 PATH 选择不改写；原有运行时目录和服务进程不因安装切换。

-- v0.2.144：开机自启动先修改并重新读取系统登录项，确认成功后才保存本机记录。
-- 沿用 SQLite settings 表（已核对 Store::open），无表结构变更，不需要手工执行。
-- 本轮未修改真实用户数据库或本机系统登录项；以下为运行时幂等语句记录。
-- INSERT INTO settings(key,value) VALUES('autostart',:value)
-- ON CONFLICT(key) DO UPDATE SET value=:value;
-- :value 为已由操作系统确认的 'true' 或 'false'；读取/修改/确认失败不执行写入。
-- 本机记录写入失败时恢复原系统状态，并向界面返回错误；界面重新读取真实状态。

-- v0.2.147：启动服务栈选择与删除保持一致；本次启动报告仅保留在桌面进程内存中。
-- 已核对 Store::open 的 SQLite 全部表及 settings/stacks 定义；无表结构变更或 migration。
-- 以下为运行时参数化语句记录，不需要手工执行；本轮不操作真实用户数据库。
-- 保存前在同一事务内确认 :stack_id 存在；空字符串表示关闭，不要求存在对应栈。
-- BEGIN IMMEDIATE;
-- SELECT EXISTS(SELECT 1 FROM stacks WHERE id=:stack_id);
-- 确认存在或 :stack_id 为空后执行；不存在时回滚，不覆盖原选择。
-- INSERT INTO settings(key,value) VALUES('startStackOnLaunch',:stack_id)
-- ON CONFLICT(key) DO UPDATE SET value=:stack_id;
-- COMMIT;
-- 删除自定义栈时，只清理仍指向该栈的启动选择，两个操作同事务提交。
-- BEGIN IMMEDIATE;
-- DELETE FROM stacks WHERE id=:stack_id AND builtin=0;
-- 仅上一条确实删除记录时执行；其他栈的启动选择保持不变。
-- UPDATE settings SET value='' WHERE key='startStackOnLaunch' AND value=:stack_id;
-- COMMIT;

-- SFTPGo 数据目录迁移：修正账号库内的物理用户目录、虚拟文件夹映射和用户组主目录。
-- 已用官方 SFTPGo 2.7.6 初始化的 SQLite schema 33 列出全部表，并确认 users、
-- folders、groups 的字段及索引。无表结构变更，不需要手工执行，不操作源账号库。
-- 以下语句仅在迁移暂存副本执行，先 PRAGMA quick_check、枚举表和检查字段；
-- 配置了 sql_tables_prefix 时对完整表名进行双引号转义后引用。
-- BEGIN IMMEDIATE;
-- UPDATE users SET home_dir=:after WHERE id=:id AND home_dir=:before;
-- UPDATE folders SET path=:after WHERE id=:id AND path=:before;
-- UPDATE groups SET user_settings=:after WHERE id=:id AND user_settings=:before;
-- :after 仅替换迁移源目录边界内的物理路径；user_settings 仅修改 JSON home_dir。
-- 保留字段原有的 TEXT/BLOB 存储形式，兼容官方程序写入的二进制 JSON。
-- 密码、权限、远程文件系统前缀、虚拟路径、配额和计数不修改。
-- 各行必须匹配一条；再次 PRAGMA quick_check 后 COMMIT，否则回滚并取消目录切换。
-- 已迁移的值不会再次替换。外部账号库和当前不支持改写的 Bolt 库在切换前返回错误。
