-- v0.2.30：数据目录迁移时的路径更新记录。
-- 不变更表结构，不对当前源数据库执行。应用先用 SQLite VACUUM INTO
-- 生成一致性快照，再在目标暂存副本的一个事务中按主键参数化更新。
-- 以下为程序使用的语句模板记录，不是需要手工执行的部署脚本。
-- :value 由完整目录边界映射产生；外部路径、密码及历史内容不作全库替换。
-- :key / :id 为原记录主键；已是目标路径的记录不会重复更新。

-- UPDATE installed SET install_path = :value WHERE key = :key;
-- UPDATE installed SET config_path = :value WHERE key = :key;
-- UPDATE sites SET root_dir = :value WHERE id = :id;
-- UPDATE sites SET runtime = :value WHERE id = :id;
-- UPDATE sites SET php_overrides = :value WHERE id = :id;
-- UPDATE certs SET cert_path = :value WHERE id = :id;
-- UPDATE certs SET key_path = :value WHERE id = :id;
-- UPDATE cron_jobs SET command = :value WHERE id = :id;
-- UPDATE cert_automations SET data = :value WHERE id = :id;

-- sites.runtime 仅修改 cwd 和 command；保留其它 JSON 字段。
-- cert_automations.data 仅修改本地部署目标的 certPath/keyPath/script。
-- pathEnvDirs 保留原值，用于首次启动新目录时精确移除原有托管 PATH 条目。

-- v0.2.32：迁移子进程初始化失败且已确认清理后，恢复目标副本的 PATH 记录。
-- 仅目标 SQLite 副本的 settings 表；没有表结构变更，不需要手工执行。
-- :value 为启动前保存的 pathEnvDirs JSON 数组，幂等恢复后供下一次激活使用。
-- INSERT INTO settings(key,value) VALUES('pathEnvDirs',:value)
-- ON CONFLICT(key) DO UPDATE SET value=:value;

-- v0.2.35：证书自动化异常中断恢复与配置更新记录。
-- 沿用当前 SQLite cert_automations 表，不新增表或字段，不需手工部署。
-- 应用取得同一任务的操作系统独占锁后，重新读取该行；只有 issuing/manual_wait
-- 且已没有锁主的任务才按中断恢复。JSON 中将 state 置为 error、enabled 置为 false，
-- 暂停 nextRenewAt，保留 manualRecords、证书结果，并新增一条有上限的执行历史。
-- 重复检查已恢复的记录不会重复写入；其它窗口仍持锁时不执行恢复。
-- 配置编辑也在该锁下核对 updatedAt，拒绝旧表单并保留后台维护的运行字段。
-- 以下是现有参数化写入模板；:data 为完整序列化 JSON，:updated_at 单调递增。
-- INSERT INTO cert_automations(id,data,updated_at) VALUES(:id,:data,:updated_at)
-- ON CONFLICT(id) DO UPDATE SET data=:data, updated_at=:updated_at;
-- 删除入口先检查任务存在和执行锁；账号密钥删除失败保留记录，入库失败恢复密钥。
-- DELETE FROM cert_automations WHERE id=:id;

-- v0.2.36：证书签发与部署分阶段记录。沿用 SQLite cert_automations.data JSON，
-- 不新增列或表；以下是应用运行时参数化语句的记录，不需手工执行。
-- 新增 deploymentId / localDeployResult 使用默认值兼容旧数据；私钥材料只保存在
-- certs/acme 的原子文件中，不放入 JSON 或配置导出。
-- 持同一任务的独占锁逐目标保存结果，updated_at 单调递增。
-- 部署中断恢复为 deploy_interrupted 并暂停；正常目标失败为 deploy_error。
-- 旧版 ok 但有失败目标、或远程专用证书有效期未知的记录，在持锁复核后仅纠正一次。
-- 导入配置时清空来源 deploymentId、localDeployResult、certId、issuedAt、expiresAt
-- 及目标的 lastResult，保持关闭；没有原证书材料时不能声称可重试部署。
-- INSERT INTO cert_automations(id,data,updated_at) VALUES(:id,:data,:updated_at)
-- ON CONFLICT(id) DO UPDATE SET data=:data, updated_at=:updated_at;
-- 删除前保存账号与材料原文，删除文件或记录失败则恢复，成功部署的站点证书不删除。
-- DELETE FROM cert_automations WHERE id=:id;
